# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/ruby/tags/
image: "slatedocs/slate"

build:
  stage: build
  script:
    - ./srv/slate/slate.sh build
  artifacts:
    expire_in: 1 week
    paths:
      - build
